### ISSUE TITLE
Ghost - Name prefix with Capital letter are not being matched

### ISSUE THREAD

**Issue by simonmekit** [singnet/opencog#31]
**Recreated from [opencog#3266](https://github.com/opencog/opencog/issues/3266)**

Words starting with capital letter inside quoted phrases are not being matched.

scheme@(guile-user) [1]> (ghost-parse "goal: (dummy_goal = 0.5)")
scheme@(guile-user) [1]> (ghost-parse "u: ( \" Dr. Watson \") How may I help you?")
scheme@(guile-user) [1]> (test-ghost "Dr. Watson")
$1 = ()
scheme@(guile-user) [1]> (ghost-parse "u: (\" dr. watson \") How may I help you?")
scheme@(guile-user) [1]> (test-ghost "Dr. Watson")
$2 = ()
scheme@(guile-user) [1]> (test-ghost "dr. watson")
[2018-07-25 13:17:49:756] [INFO] [say] (How may I help you ?)
$3 = ((WordNode "How")
 (WordNode "may")
 (WordNode "I")
 (WordNode "help")
 (WordNode "you")
 (WordNode "?")
)
scheme@(guile-user) [1]>

**Comment by leungmanhin** [comment]
I'll look into this

**Comment by simonmekit** [comment]
running using `ghost-parse-file` command has also similar behavior. I think it can be treated in similar way like the one you fixed [here](https://github.com/opencog/opencog/issues/3050).

**Comment by leungmanhin** [comment]
Yes this is also related to how the actual sentence is parsed, e.g. "Dr." and "dr." are different, while authors would consider them to be the same as in a case insensitive string match.

**Comment by leungmanhin** [comment]
Should be fixed in https://github.com/singnet/opencog/pull/33

**Comment by simonmekit** [comment]
yes #33 solves it.
