### ISSUE TITLE
Ghost - Negation in the middle of sentence

### ISSUE THREAD

**Issue by EskenderTamrat** [singnet/opencog#37]
**Recreated from https://github.com/opencog/opencog/issues/3269 **

Negation (unless it is in the start of sentence) gives syntax error

`scheme@(guile-user) > (ghost-parse "u: ( !never eat meat ) good ^keep") 
scheme@(guile-user) > (ghost-parse "u: ( I !never eat meat ) good ^keep")
ERROR: In procedure scm-error:
Syntax error: unexpected token :  #<lexical-token category: NOT source: #<source-location input: #f line: 0 column: 6 offset: 35 length: #f> value: #f>
`

**Comment by leungmanhin** [comment]
The syntax of the rule is not valid indeed. Negation checks for absence of words for the whole input, but not between two words.

**Comment by EskenderTamrat** [comment]
Yeah, that's correct. But this also leads to a similar syntax error if we want to check absence of two or more words like the ff.

`guile> (ghost-parse "u: (!never !not hello) answer ^keep")`

**Comment by leungmanhin** [comment]
It should be written as `(![never not] hello)` if you want to exclude more than one word

**Comment by EskenderTamrat** [comment]
Thanks. I'm closing the issue.
